# Generated by Django 2.2.5 on 2020-08-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200830_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_4',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_5',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_1',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_2',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_3',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_3',
            field=models.IntegerField(default=0),
        ),
    ]
