# Generated by Django 2.2.5 on 2020-08-31 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200831_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='country',
        ),
    ]
