# Generated by Django 2.2.5 on 2020-08-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200816_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Room Type'},
        ),
    ]
