# Generated by Django 2.2.5 on 2020-08-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20200819_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='menu_1',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='room',
            name='menu_2',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='room',
            name='menu_3',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='room',
            name='menu_4',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='room',
            name='menu_5',
            field=models.CharField(max_length=140),
        ),
    ]
