# Generated by Django 2.2.5 on 2020-08-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_auto_20200819_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='menu_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='menu_2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='menu_3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='menu_4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='menu_5',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_5',
        ),
    ]
