# Generated by Django 2.2.5 on 2020-08-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_auto_20200819_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='menu_1',
            field=models.CharField(default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='menu_2',
            field=models.CharField(default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='menu_3',
            field=models.CharField(default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='menu_4',
            field=models.CharField(default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='menu_5',
            field=models.CharField(default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_1',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_2',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_3',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_4',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_5',
            field=models.IntegerField(default='', null=True),
        ),
    ]
