# Generated by Django 2.2.5 on 2020-08-04 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_auto_20200803_1533"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="message", new_name="message",
        ),
        migrations.AlterField(
            model_name="message",
            name="Conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="conversations.Conversation",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
