# Generated by Django 2.2.5 on 2020-08-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_auto_20200804_1239"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="message", new_name="message",
        ),
    ]
