# Generated by Django 2.2.5 on 2020-08-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Value',
            new_name='value',
        ),
    ]
