# Generated by Django 2.2.5 on 2020-08-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20200803_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
